[mgr]
ratio = [1,2,5]

[opener]
play = [
	{ run = "mpv --force-window  %s1", orphan = true, for = "unix" },
]
edit = [
	{ run = "$EDITOR %s", block = true, for = "unix" },
]
view = [
  { run = "oculante %d1", orphan = true, for = "unix"  }
]
extract = [
	{ run = 'ouch d -y "%s1"', orphan = true,  desc = "Extract here with ouch", for = "unix" },
]
open = [
	{ run = "xdg-open %s", desc = "Open" },
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
  { mime = "image/*", use = "view" },
	{ mime = "{video,audio}/*", use = "play" },
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", use = "extract" },
	{ url = "*.json", use = "edit" },

]

[plugin]
prepend_preloaders = [
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
]

prepend_previewers = [
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run = "ouch" },
]

[tasks]
image_alloc = 1073741824 # = 1024*1024*1024 = 1024MB
