# fonts settigns
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 16

# cursor
cursor_shape beam
cursor_trail 1

# window
remember_window_size  no
initial_window_width  700
initial_window_height 480
tab_bar_style hidden
background_opacity 0.7
enabled_layouts splits
inactive_text_alpha 0.5

# keybinds
clear_all_shortcuts yes
kitty_mod ctrl+shift

# panes
map kitty_mod+[ launch --cwd=current --location=vsplit
map kitty_mod+] launch --cwd=current --location=hsplit
map kitty_mod+q close_window
map kitty_mod+down previous_window
map kitty_mod+up next_window

# tabs
map kitty_mod+t new_tab
map kitty_mod+w close_tab
map ctrl+tab next_tab
map kitty_mod+tab previous_tab

# miscellaneous
map kitty_mod+p command_palette
map kitty_mod+r load_config_file
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
