[mgr]
ratio = [1,2,5]

[plugin]
prepend_preloaders = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
]
prepend_previewers = [
  { mime = "{audio,video,image}/*", run = "mediainfo"},
  { mime = "application/subrip", run = "mediainfo" },
  
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run  = "ouch --show-file-icons" }
]

[opener]
extract = [
	{ run = 'ouch d -y "$s1"', desc = "Extract here with ouch", for = "unix" },
]
play = [
	{ run = "mpv %s", orphan = true, for = "unix" },
]
edit = [
	{ run = "$EDITOR %s", block = true, for = "unix" },
]
open = [
	{ run = "xdg-open %s1", desc = "Open" },
]
view = [
  { run = "oculante %s1", orphan = true, for = "unix" }
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
  { mime = "image/*", use = "view" },
	{ mime = "{audio,video}/*", use = "play" },
	{ url = "*.json", use = "edit" },
  { url = "*", use = "open" },
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", use = "extract" }
]

[tasks]
image_alloc      = 1073741824        # = 1024*1024*1024 = 1024MB
