
# Lazydot Configuration File

# Path to the dotfiles folder (must start with ~/)
dotfolder_path = "~/.dots"

# List of dotfile paths to manage (each must start with ~/ or /)
# paths = [
#     "~/example/.bashrc","
#     "~/example/.bashrc",
#     "~/example/.vimrc",
# ]
paths = ["~/.config/lazydot.toml", "~/.config/helix/config.toml", "~/.config/helix/languages.toml", "~/.config/matugen/config.toml", "~/.config/matugen/templates/tuios.json", "~/.config/matugen/templates/ghgrab.toml", "~/.config/matugen/templates/termusic.yml", "~/.config/niri/keybinds.kdl", "~/.config/niri/rules.kdl", "~/.config/niri/layout.kdl", "~/.config/niri/config.kdl", "~/.config/noctalia/settings.json", "~/.config/noctalia/plugins.json", "~/.config/nushell/config.nu", "~/.config/kitty/kitty.conf", "~/.config/fastfetch", "~/.config/yazi/yazi.toml", "~/.config/yazi/package.toml"]

[defaults]
# Behavior when a duplicate file is found at the destination:
# - ask: Prompt the user to decide
# - overwritehome: Overwrite the file in HOME with the dotfolder version
# - overwritedotfile: Overwrite the dotfolder copy with the HOME version
# - backuphome: Backup the HOME file before overwriting
# - skip: Do nothing and skip the conflict
on_duplicate = "ask"

# Behavior after a link is disabled (delinked):
# - remove: Remove the file from the dotfolder after restoring it to HOME (default)
# - keep: Keep the file in the dotfolder even after restoring it to HOME
on_delink = "remove"
