theme = "noctalia"

[editor.soft-wrap]
enable = true

[keys.insert]
A-a = "goto_line_start"
"A-;" = "goto_line_end"
A-h = "move_char_left"
A-l = "move_char_right"
A-k = "move_visual_line_up"
A-j = "move_visual_line_down"
A-n = "normal_mode"
A-r = ":config-reload"
"home" = ":noop"
"end" = ":noop"
